---
title: "Inspiratie"
---

<hr>

### Presentatie

<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe width="360" height="200" src="https://docs.google.com/presentation/d/e/2PACX-1vQPhf4h-t4L1-SE2CCtvOPy-5WuKW8BnwQgPc7pzK9lp9Keqdk1leRiKXvQ2hfcT4NYj4sqey58OU6b/embed?start=true&loop=true&delayms=7000" frameborder="0" allowfullscreen></iframe></div>

<hr>

### Teachable Machine 2.0

<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src="https://www.youtube.com/embed/T2qQGqZxkD0" frameborder="0" allowfullscreen></iframe></div>

<hr>

### Andrew Ng

<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src="https://www.youtube.com/embed/NKpuX_yzdYs" frameborder="0" allowfullscreen></iframe></div>

<hr>

### Google

<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe width="360" height="200" src="https://www.youtube.com/embed/-O-E1nFm6-A" frameborder="0" allowfullscreen></iframe></div>